language: python
sudo: false
cache: pip

python:
    - 3.6.2

install:
    - pip install -U pylava
    - pip install -U https://github.com/eliasfrank/humanify/archive/master.zip

script:
    - pylava
    - ./tests/unitest.py
